version: 0.2
env:
  variables:
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r scripts/requirements.txt
  build:
    commands:
      - echo Actualizando base de datos callejero.duckdb...
      - python scripts/download_callejero.py
