version: 0.2
env:
  variables:
    # IMAGE_REPO_NAME: Se pasa como variable de entorno desde la consola de CodeBuild
    # ACCOUNT_ID: Se pasa como variable de entorno desde la consola de CodeBuild
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - echo Logging en ECR...
      - echo $REPO_URI
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Construyendo Imagen Docker...
      - cd api_rest
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Subiendo inagen a ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
